/* Generated By:JJTree: Do not edit this line. ASTAssignee.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTAssignee extends SimpleNode {
  public ASTAssignee(int id) {
    super(id);
  }

  public ASTAssignee(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab6452be83d7dfef17fa122252a08fd3 (do not edit this line) */
