/* Generated By:JJTree: Do not edit this line. ASTArraySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTArraySuffix extends SimpleNode {
  public ASTArraySuffix(int id) {
    super(id);
  }

  public ASTArraySuffix(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f459aa567226e46f6428474be5e57e26 (do not edit this line) */
