/* Generated By:JJTree: Do not edit this line. ASTAndOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTAndOperator extends SimpleNode {
  public ASTAndOperator(int id) {
    super(id);
  }

  public ASTAndOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d6405263bc4dedd169c863f89c815d6 (do not edit this line) */
