/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTArrayType extends SimpleNode {
  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2bd47d5c6294d7f3f686f901437d042 (do not edit this line) */
