/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTBool extends SimpleNode {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9deec210d5457ed239352c19df628a86 (do not edit this line) */
