/* Generated By:JJTree: Do not edit this line. ASTCharLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTCharLiteral extends SimpleNode {
  public ASTCharLiteral(int id) {
    super(id);
  }

  public ASTCharLiteral(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0de6b34f7ed5b90326bbf8c79b0ecb6 (do not edit this line) */
