/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTContinueStatement extends SimpleNode {

    public ASTContinueStatement(int id) {
        super(id);
    }

    public ASTContinueStatement(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=e41202b63861198fe770de0b5e00e08a (do not edit this line) */
