/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTClass extends SimpleNode {
  
  String name;
  String extending;
  
  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(CZECHJavaParser p, int id) {
    super(p, id);
  }

  public String getName() {
    return name;
  }

  public String getExtending() {
    return extending;
  }
}
/* JavaCC - OriginalChecksum=49113ebbeb754bcf6e90eecb28ade78b (do not edit this line) */
