/* Generated By:JJTree: Do not edit this line. ASTChar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTChar extends SimpleNode {
  public ASTChar(int id) {
    super(id);
  }

  public ASTChar(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46ed652cb9a54fea907d24a9aca4cf23 (do not edit this line) */
