/* Generated By:JJTree: Do not edit this line. ASTDebugStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTDebugStatement extends SimpleNode {
  public ASTDebugStatement(int id) {
    super(id);
  }

  public ASTDebugStatement(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47c6d0cfa1be60fad40b0e109af13e33 (do not edit this line) */
