/* Generated By:JJTree: Do not edit this line. ASTDivideOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTDivideOperator extends SimpleNode {
  public ASTDivideOperator(int id) {
    super(id);
  }

  public ASTDivideOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4329624315cef82a840089330a894e2 (do not edit this line) */
