/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTEmptyStatement extends SimpleNode {

    public ASTEmptyStatement(int id) {
        super(id);
    }

    public ASTEmptyStatement(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=68289fae5df09b6477b4e17220cd3af9 (do not edit this line) */
