/* Generated By:JJTree: Do not edit this line. ASTEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTEqualOperator extends SimpleNode {
  public ASTEqualOperator(int id) {
    super(id);
  }

  public ASTEqualOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffd039bb696c258252473bbca668cde5 (do not edit this line) */
