/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTFloatLiteral extends SimpleNode {
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0060f7affb18ddd8b3ac6bd1c93c430a (do not edit this line) */
