/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOrEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTGreaterThanOrEqualOperator extends SimpleNode {
  public ASTGreaterThanOrEqualOperator(int id) {
    super(id);
  }

  public ASTGreaterThanOrEqualOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79fc9ecfd4d0e3d119d302d09c24dadf (do not edit this line) */
