/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTInstanceOfExpression extends SimpleNode {

    public ASTInstanceOfExpression(int id) {
        super(id);
    }

    public ASTInstanceOfExpression(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=d06b69086a67d1e7572622b5bdfbcf2e (do not edit this line) */
