/* Generated By:JJTree: Do not edit this line. ASTLessThanOrEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTLessThanOrEqualOperator extends SimpleNode {
  public ASTLessThanOrEqualOperator(int id) {
    super(id);
  }

  public ASTLessThanOrEqualOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16d2349f9e19b2b13a3ff51574756a93 (do not edit this line) */
