/* Generated By:JJTree: Do not edit this line. ASTLessThanOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTLessThanOperator extends SimpleNode {
  public ASTLessThanOperator(int id) {
    super(id);
  }

  public ASTLessThanOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e0eb46be3dbcc12beaf050afcc735be (do not edit this line) */
