/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTLiteral extends SimpleNode {

    public ASTLiteral(int id) {
        super(id);
    }

    public ASTLiteral(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=99cc21bda0b563b1ef6c8aebcfb335b2 (do not edit this line) */
