/* Generated By:JJTree: Do not edit this line. ASTMultiplyOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTMultiplyOperator extends SimpleNode {
  public ASTMultiplyOperator(int id) {
    super(id);
  }

  public ASTMultiplyOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b6f9a31817465f9fcaf28127527d45a (do not edit this line) */
