/* Generated By:JJTree: Do not edit this line. ASTMinusOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTMinusOperator extends SimpleNode {
  public ASTMinusOperator(int id) {
    super(id);
  }

  public ASTMinusOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d38d96c26d860b5663032c4c85fea585 (do not edit this line) */
