/* Generated By:JJTree: Do not edit this line. ASTNotEqualOperator.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTNotEqualOperator extends SimpleNode {

    public ASTNotEqualOperator(int id) {
        super(id);
    }

    public ASTNotEqualOperator(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=b350dfd0f9d03ee060a7f7bcf10fd6bd (do not edit this line) */
