/* Generated By:JJTree: Do not edit this line. ASTNotEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTNotEqualOperator extends SimpleNode {
  public ASTNotEqualOperator(int id) {
    super(id);
  }

  public ASTNotEqualOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9b4705d83f25813d380a4872a473b25 (do not edit this line) */
