/* Generated By:JJTree: Do not edit this line. ASTName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e38b6d3ea19b4b4bcea97f047d4f62b8 (do not edit this line) */
