/* Generated By:JJTree: Do not edit this line. ASTNameList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3db1bd6d20f2e201ffdb048e86ae1834 (do not edit this line) */
