/* Generated By:JJTree: Do not edit this line. ASTNegationOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTNegationOperator extends SimpleNode {
  public ASTNegationOperator(int id) {
    super(id);
  }

  public ASTNegationOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31f208bfe53c60bbc6eedd679bbe224a (do not edit this line) */
