/* Generated By:JJTree: Do not edit this line. ASTNumberLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTNumberLiteral extends SimpleNode {
  public ASTNumberLiteral(int id) {
    super(id);
  }

  public ASTNumberLiteral(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0fe3f5446758a3e95c60d9f0b3bca83e (do not edit this line) */
