/* Generated By:JJTree: Do not edit this line. ASTOrOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTOrOperator extends SimpleNode {
  public ASTOrOperator(int id) {
    super(id);
  }

  public ASTOrOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90e1192501ba176575bc60da96da42a3 (do not edit this line) */
