/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpression.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTPrimaryExpression extends SimpleNode {

    public ASTPrimaryExpression(int id) {
        super(id);
    }

    public ASTPrimaryExpression(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=abba5c8d9c412d0c17e4af3a9d701c1f (do not edit this line) */
