/* Generated By:JJTree: Do not edit this line. ASTPlusOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTPlusOperator extends SimpleNode {
  public ASTPlusOperator(int id) {
    super(id);
  }

  public ASTPlusOperator(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2491977f81d0e26837c98eeaa5b94bdf (do not edit this line) */
