/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e427cdc9809f571e8cc6047bc33fc3d9 (do not edit this line) */
