/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTReturnStatement extends SimpleNode {

    public ASTReturnStatement(int id) {
        super(id);
    }

    public ASTReturnStatement(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=327d0027844722cafb14df8d8d4af3ec (do not edit this line) */
