/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTStringLiteral extends SimpleNode {

    public ASTStringLiteral(int id) {
        super(id);
    }

    public ASTStringLiteral(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=aba64e61694f0dcfbfcee5def3b04cd9 (do not edit this line) */
