/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionList.java Version 6.0 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTStatementExpressionList extends SimpleNode {

    public ASTStatementExpressionList(int id) {
        super(id);
    }

    public ASTStatementExpressionList(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=dae7fdd5f7302918a0399543aed254d5 (do not edit this line) */
