/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTSwitchLabel extends SimpleNode {
  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e22742e9a113fa42c7ebd38fa6e25fb3 (do not edit this line) */
