/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTSwitchStatement extends SimpleNode {
  public ASTSwitchStatement(int id) {
    super(id);
  }

  public ASTSwitchStatement(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acee33cec37cea7ca5d0a74efd7e444a (do not edit this line) */
