/* Generated By:JJTree: Do not edit this line. ASTSuper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTSuper extends SimpleNode {
  public ASTSuper(int id) {
    super(id);
  }

  public ASTSuper(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ace336a85fdb038e48dd8f2c6940b3a (do not edit this line) */
