/* Generated By:JJTree: Do not edit this line. ASTStatic.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTStatic extends SimpleNode {
  public ASTStatic(int id) {
    super(id);
  }

  public ASTStatic(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aec7ef0cfa23a60ef4862f9417d2adf5 (do not edit this line) */
