/* Generated By:JJTree: Do not edit this line. ASTTrue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public
class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(CZECHJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da26790793c8f0025256fc6504e76a6a (do not edit this line) */
