/* Generated By:JJTree: Do not edit this line. ASTThis.java Version 4.3 */
 /* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.fit.cvut.czechjava.parser;

public class ASTThis extends SimpleNode {

    public ASTThis() {
        super(0);
    }

    public ASTThis(int id) {
        super(id);
    }

    public ASTThis(CZECHJavaParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=0acc766c4161361302e17a61be27afcc (do not edit this line) */
